Wrote 'exit code' code
The exit code of the fdisk wrapper script is now the same as the
last, non-zero exit code of the 'fdisk -l $DEVICE' command

diff --git a/fdisk b/fdisk
--- a/fdisk
+++ b/fdisk
@@ -14,6 +14,10 @@ DEVICES_TO_SKIP=''
 #these extra checks
 IMITATE_FDISK=false
 
+#Exit Code. Changes automatically
+#depending on how real fdisk exits
+EXIT_CODE=0
+
 [[ -e $FDISK_PATH ]] ||
 { echo "$FDISK_PATH is not a valid path to fdisk. Modify $0 with the correct path."; exit 1; }
 
@@ -57,6 +61,10 @@ else
 		if ! $SKIP
 		then
 			$FDISK_PATH -l $DEVICE
+			EC=$?
+			[[ $EC == 0 ]] || EXIT_CODE=$EC
 		fi
 	done
 fi
+
+exit $EXIT_CODE
